name: MTApp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_spinkit: "^4.1.2"
  mapbox_search: ^2.0.1
  fluttertoast: ^7.1.1
  search_map_place: ^0.3.0
  google_maps_place_picker: ^0.10.0
  google_maps_flutter: ^0.5.32
  google_fonts: ^1.1.0
  http: ^0.12.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  uses-material-design: true
